feat: ✨ Standardize github action build flow between platforms

diff --git a/.github/workflows/Build-and-deploy-linux.yml b/.github/workflows/Build-and-deploy-linux.yml
--- a/.github/workflows/Build-and-deploy-linux.yml
+++ b/.github/workflows/Build-and-deploy-linux.yml
@@ -23,8 +23,10 @@ jobs:
 
       - uses: conda-incubator/setup-miniconda@v2
         with:
+          miniconda-version: "latest"
           activate-environment: env-electron-python
           environment-file: tools/anaconda-env/environment-Linux.yml
+          auto-update-conda: true
           auto-activate-base: false
       - run: |
           conda info
@@ -37,9 +39,36 @@ jobs:
       - name: Install package.json modules and their dependencies
         run: npm install --ignore-scripts
 
-      - name: Build and deploy on Linux
+      - name: Build the python server executable
+        run: |
+          npm run python-onefile-build-unix
+
+      - name: Test the python server executable
+        run: |
+          # Run the executable in the background
+          ./pyflaskdist/app.exe 4242 > server_output.txt 2>&1 &
+
+          # Wait for the server to start
+          sleep 30
+
+          # Display the server output
+          cat server_output.txt
+
+          # Check the server output for the "Running on" line
+          if grep -q "Running on http://127.0.0.1:4242/" server_output.txt; then
+            echo "Server started successfully."
+          else
+            echo "Error: Server failed to start."
+            # You can perform additional error handling or cleanup here if needed
+            # For example, you may want to exit the workflow with an error code
+            exit 1
+          fi
+
+          # Clean up the temporary output file
+          rm server_output.txt
+
+      - name: Deploy the application
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          npm run python-onefile-build
           npm run deploy-linux
